### PR TITLE
Generator-PC

### PR DESCRIPTION
**Pull request by NycuRO**

### CODE REVIEW

**Comment by Creeperface01** [comment]
Why

**Comment by NycuRO** [comment]
@Creeperface01 I want to port all generator from PC.

I need materials for IBlockStateProprietes.

**Comment by NycuRO** [comment]
@caspervanneck And i want to use plugin folders ,not Nukkit ,because isn't complex as pc.

**Comment by Creeperface01** [comment]
Sorry but absolutely useless changes

**Comment by NycuRO** [comment]
@Creeperface01 Yes but i need for Noise Generator

**Comment by Creeperface01** [comment]
You dont

**Comment by Creeperface01** [comment]
You have to think

**Comment by caspervanneck** [comment]
Not useless

**Pull request closed without merging**
